name: PHP Code Style Fixer

on:
  workflow_dispatch:

  pull_request:
    branches:
      - 'master'
      - 'dev'

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6

